# Generated by Django 4.2.9 on 2024-02-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_outlet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='google_link',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='latitude',
            field=models.FloatField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='longitude',
            field=models.FloatField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='opening_hours',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='waze_link',
            field=models.TextField(blank=True, default=''),
        ),
    ]
